FROM node:16-alpine

# Crear y establecer el directorio de trabajo
WORKDIR /usr/src/app

# Copiar package.json y package-lock.json
COPY package*.json ./
COPY nutriscan-71493-firebase-adminsdk-ugmom-589ff76776.json /usr/src/app/nutriscan-71493-firebase-adminsdk-ugmom-589ff76776.json

# Instalar dependencias
RUN npm install

# Copiar todo el código al contenedor
COPY . .

# Exponer el puerto
EXPOSE 3000

# Comando para iniciar la aplicación
CMD ["node", "src/index.js"]
